---
# action.yml
name: "Leanpub Multi Action"
description: "Interact with Leanpub.com via GitHub Actions."
inputs:
  leanpub-api-key:
    description: "Leanpub API Key"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
