---
# action.yml
name: "Leanpub Multi Action"
description: "Interact with Leanpub.com via GitHub Actions."
inputs:
  leanpub-api-key:
    description: "Leanpub API Key"
    required: true
  leanpub-book-slug:
    description: "Leanpub Book Slug"
    required: true
  preview:
    description: "Start a Preview job"
    required: false
    default: false
runs:
  using: "docker"
  image: "docker://ghcr.io/lykinsbd/leanpub-multi-action:latest"
  # args:
  #   - "${{ inputs.leanpub-api-key }}"
  #   - "${{ inputs.leanpub-book-slug }}"
  #   - "${{ inputs.preview }}"
