---
# This action will cut a release based on a tagged commit that starts with "v"
name: "Publish Artifacts to Github"

"on":
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - "v*"

jobs:
  publish_python:
    name: "Publish Python Artifacts"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "./.github/actions/setup-environment"
      - name: "Set version environment variable"
        run: "echo RELEASE_VERSION=${GITHUB_REF:10} >> $GITHUB_ENV"
      - name: "Run poetry version"
        run: "poetry version ${{ env.RELEASE_VERSION }}"
      - name: "Run poetry build"
        run: "poetry build"
      - name: "Upload binaries to release"
        uses: "softprops/action-gh-release@v1"
        with:
          files: "dist/*"
          body_path: "NEWS.rst"
  publish_container:
    name: "Publish Container Artifacts"
    runs-on: "ubuntu-20.04"
    env:
      REGISTRY: "ghcr.io"
      IMAGE_NAME: "${{ github.repository }}"

    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set version environment variable"
        run: "echo RELEASE_VERSION=${GITHUB_REF:10} >> $GITHUB_ENV"
      - name: "Set Python package name environment variable"
        run: 'echo "PACKAGE_NAME=$(echo ${GITHUB_REPOSITORY#*\/} | tr - _)" >> $GITHUB_ENV'  # yamllint disable-line rule:quoted-strings
      - name: "Gather Python release"
        run: |
          curl -L -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://github.com/${{ env.GITHUB_REPOSITORY }}/releases/download/${{ env.RELEASE_VERSION }}/${{ env.PACKAGE_NAME }}-${{ env.RELEASE_VERSION }}-py3-none-any.whl" \
          -o "${{ env.PACKAGE_NAME }}-${{ env.RELEASE_VERSION }}-py3-none-any.whl"
      - name: "Gather Docker metadata"
        id: "meta"
        uses: "docker/metadata-action@v3"
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: "Login to ghcr.io"
        uses: "docker/login-action@v1"
        with:
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Build and push container"
        uses: "docker/build-push-action@v2"
        with:
          context: "."
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
          build-args: |
            LMA_VERSION=${{ env.RELEASE_VERSION }}
    needs:
      - "publish_python"
