---
# This action will run the integration and unit tests, as well as all linters
name: "Test Runner"

"on":
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

jobs:
  run_tests:
    runs-on: "ubuntu-latest"
    name: "Run Tests"
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Launch Container"
        uses: "./"  # Uses an action in the root directory
        with:
          entrypoint: "invoke tests --local"
